owner: PhilRoli
repo: rettstat-status

sites:
  - name: RettStat Produktion (Frontend)
    url: https://rettstat.at
    slug: production-frontend

  - name: RettStat Produktion (Backend API)
    url: https://api.rettstat.at/version
    slug: production-backend

  - name: RettStat Entwicklung (Frontend)
    url: https://dev.rettstat.at
    slug: development-frontend

  - name: RettStat Entwicklung (Backend API)
    url: https://api.dev.rettstat.at/version
    slug: development-backend

status-website:
  cname: status.rettstat.at
  name: RettStat Status
  theme: light
  introTitle: RettStat Systemstatus
  introMessage: Aktuelle Verfügbarkeit aller RettStat-Dienste.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/PhilRoli/rettstat-status

i18n:
  up: Betrieb
  down: Ausfall
  degraded: Beeinträchtigt
